# For settings, refer to `https://qiita.com/delphinus/items/cd221a450fd23506e81a`   

# LSP クライアント本体
[[plugins]]
repo = 'prabirshrestha/vim-lsp'

# LSP サーバーを自動インストール・設定してくれる神プラグイン
[[plugins]]
repo = 'mattn/vim-lsp-settings'

# 補完エンジン本体
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

# 補完エンジンとLSPを繋ぐ
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'


[[plugins]]
repo = "w0ng/vim-hybrid"

[[plugins]]
repo = "itchyny/lightline.vim"

[[plugins]]
repo = "dhruvasagar/vim-table-mode"

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = "cespare/vim-toml"

[[plugins]]
repo = "psf/black"


[[plugins]]
repo = "sillte/vim-pytoy"
hook_add = """
command! -nargs=0 Qsort python3 import pytoy; pytoy.quickfix_timesort()
"""
